<?php declare(strict_types=1);
/**
 * @var \Elgentos\Lightspeed\Block\ItemsWithPattern $block
 */

?>
<noscript id="deferred-styles">
    <?= $block->render() ?>
</noscript>
<script>
    (function(){
        var raf = window.requestAnimationFrame || window.mozRequestAnimationFrame ||
            window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;

        function loadDeferredStyles() {
            var addStylesNode = document.getElementById("deferred-styles"),
                replacement = document.createElement("div");

            replacement.innerHTML = addStylesNode.textContent;

            document.body.appendChild(replacement);
            addStylesNode.parentElement.removeChild(addStylesNode);
        }

        if (raf) {
            raf(function() {window.setTimeout(loadDeferredStyles, 0)});
        } else {
            window.addEventListener('load', loadDeferredStyles);
        }
    })();
</script>
